//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockZilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class achats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public achats()
        {
            this.detailsachat = new HashSet<detailsachat>();
        }
    
        public int Id { get; set; }
        public System.DateTime date_achats { get; set; }
        public int id_fourn { get; set; }
        public int id_acheteur { get; set; }
        public Nullable<int> remise { get; set; }
        public System.DateTime date_livraison { get; set; }
        public bool livre { get; set; }
        public Nullable<int> num_commande { get; set; }
    
        public virtual users users_fourn { get; set; }
        public virtual users users_acheteur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detailsachat> detailsachat { get; set; }
    }
}
