//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockZilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detailsachat
    {
        public int Id { get; set; }
        public int id_achats { get; set; }
        public int id_produit { get; set; }
        public Nullable<int> nb_achat { get; set; }
        public Nullable<double> prix_ht { get; set; }
        public Nullable<int> tva { get; set; }
        public Nullable<int> remise { get; set; }
    
        public virtual achats achats { get; set; }
        public virtual produits produits { get; set; }
    }
}
