//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockZilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produits()
        {
            this.detailsachat = new HashSet<detailsachat>();
            this.detailsvente = new HashSet<detailsvente>();
        }
    
        public int Id { get; set; }
        public string nom_prod { get; set; }
        public int id_categorie { get; set; }
        public Nullable<int> qte_prod { get; set; }
        public Nullable<double> prix_moyen { get; set; }
    
        public virtual catego catego { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detailsachat> detailsachat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detailsvente> detailsvente { get; set; }
    }
}
